[package]
name = "hyperlane-core"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
auto_impl = "1.0"
bytes = { version = "1", features = ["serde"]}
config.workspace = true
convert_case = "0.6"
derive-new.workspace = true
ethers-providers.workspace = true
ethers-signers.workspace = true
ethers.workspace = true
eyre.workspace = true
hex = "0.4.3"
itertools.workspace = true
num = {version="0", features=["serde"]}
num-derive.workspace = true
num-traits.workspace = true
rocksdb.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3 = "0.10"
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
tracing-futures.workspace = true
tracing.workspace = true

# version determined by ethers-rs
primitive-types = "*"
lazy_static = "*"

[dev-dependencies]
hyperlane-base = { path = "../hyperlane-base"}
tokio = { workspace = true, features = ["rt", "time"] }
walkdir = { version = "2" }

[features]
default = ["eq-separator", "combined-flags"]
output = []

# argument parsing
eq-separator = []
combined-flags = []
#disabled to prevent changing things when using cargo check --all-features as we do not currently support this
#short-space-opt = []
