[package]
name = "hyperlane-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_impl = "1.0"
ethers = { git = "https://github.com/hyperlane-xyz/ethers-rs", branch = "mattie/better-debug-logging" }
ethers-signers = { git = "https://github.com/hyperlane-xyz/ethers-rs", branch = "mattie/better-debug-logging", features=["aws"] }
ethers-providers = { git = "https://github.com/hyperlane-xyz/ethers-rs", branch = "mattie/better-debug-logging", features=["ws", "rustls"] }
config = "~0.13.3"
hex = "0.4.3"
sha3 = "0.10"
lazy_static = "*"
thiserror = "1.0"
async-trait = { version = "0.1", default-features = false }
tokio = { version = "1", features = ["rt", "macros"] }
tracing = "0.1"
tracing-futures = "0.2"
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
rocksdb = "0.18"
bytes = { version = "1", features = ["serde"]}
num = {version="0", features=["serde"]}
num-traits = "0.2"
num-derive = "0.3"
strum = "0.24"
strum_macros = "0.24"

# version determined by ethers-rs
primitive-types = "*"

[dev-dependencies]
hyperlane-base = { path = "../hyperlane-base" }
tokio = {version = "1", features = ["rt", "time"]}
walkdir = { version = "2" }

[features]
output = []
