cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-ethereum"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
# Main block
async-trait.workspace = true
derive-new.workspace = true
ethers-contract.workspace = true
ethers-core.workspace = true
ethers-signers.workspace = true
ethers.workspace = true
futures-util.workspace = true
hex.workspace = true
num.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing-futures.workspace = true
tracing.workspace = true
url.workspace = true

hyperlane-core = { path = "../../hyperlane-core" }
ethers-prometheus = { path = "../../ethers-prometheus", features = ["serde"] }
num-traits.workspace = true

[build-dependencies]
abigen = { path = "../../utils/abigen", features = ["ethers"] }
hyperlane-core = { path = "../../hyperlane-core", features = ["test-utils"] }
