warpRouteId: USDC/aleo

strategy:
  rebalanceStrategy: weighted
  chains:
    arbitrum:
      weighted:
        weight: 20
        tolerance: 5
      bridgeLockTime: 60
      bridgeMinAcceptedAmount: 3500
      bridge: '0xE086378F7f0afd5C3ff95E10B5e7806a0901b33f'

    avalanche:
      weighted:
        weight: 10
        tolerance: 5
      bridgeLockTime: 60
      bridgeMinAcceptedAmount: 3500
      bridge: '0xCB35d7730843F770625bE36A0E4228c17fDcBC09'

    base:
      weighted:
        weight: 20
        tolerance: 5
      bridgeLockTime: 60
      bridgeMinAcceptedAmount: 3500
      bridge: '0x31169ee5A8C0D680de74461d7B5394fFc7C3576B'

    ethereum:
      weighted:
        weight: 30
        tolerance: 5
      bridgeLockTime: 60
      bridgeMinAcceptedAmount: 3500
      bridge: '0x7A576Bb5291567cfDbB4585B1911CF7C9891ea07'

    optimism:
      weighted:
        weight: 10
        tolerance: 5
      bridgeLockTime: 60
      bridgeMinAcceptedAmount: 3500
      bridge: '0x4eFaacbf0D3d57b401Cb6B559e84b344448b0C30'

    polygon:
      weighted:
        weight: 10
        tolerance: 5
      bridgeLockTime: 60
      bridgeMinAcceptedAmount: 3500
      bridge: '0x07d89DE0F7E18c9bcAAE81F44aee9CA02EBeE872'
