warpRouteId: USDC/eclipsemainnet
strategy:
  rebalanceStrategy: weighted
  chains:
    ethereum:
      weighted:
        weight: 29
        tolerance: 5
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 3500
      bridge: '0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23'
      executionType: movableCollateral

    base:
      weighted:
        weight: 24
        tolerance: 5
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 3500
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'
      executionType: movableCollateral

    arbitrum:
      weighted:
        weight: 17
        tolerance: 5
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 3500
      bridge: '0x4c19c653a8419A475d9B6735511cB81C15b8d9b2'
      executionType: movableCollateral

    optimism:
      weighted:
        weight: 10
        tolerance: 5
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 3500
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'
      executionType: movableCollateral

    polygon:
      weighted:
        weight: 5
        tolerance: 3
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 2500
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'
      executionType: movableCollateral

    unichain:
      weighted:
        weight: 10
        tolerance: 5
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 3500
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'
      executionType: movableCollateral

    ink:
      weighted:
        weight: 5
        tolerance: 3
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 2500
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'
      executionType: movableCollateral
