warpRouteId: USDC/eni

strategy:
  rebalanceStrategy: minAmount
  chains:
    arbitrum:
      minAmount:
        min: 1000
        target: 2000
        type: 'absolute'
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 500
      bridge: '0x4c19c653a8419A475d9B6735511cB81C15b8d9b2'

    base:
      minAmount:
        min: 1000
        target: 2000
        type: 'absolute'
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 500
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'

    ethereum:
      minAmount:
        min: 1000
        target: 2000
        type: 'absolute'
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 500
      bridge: '0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23'

    optimism:
      minAmount:
        min: 1000
        target: 2000
        type: 'absolute'
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 500
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'

    polygon:
      minAmount:
        min: 1000
        target: 2000
        type: 'absolute'
      bridgeLockTime: 1800
      bridgeMinAcceptedAmount: 500
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'
