warpRouteId: USDC/incentiv
strategy:
  rebalanceStrategy: weighted
  chains:
    arbitrum:
      weighted:
        weight: 20
        tolerance: 5 # 5% deviation on the expected balance before triggering a rebalance
      bridgeLockTime: 1800 # 30 mins in seconds (required for CCTP latency)
      bridgeMinAcceptedAmount: 3500
      bridge: '0x8a82186EA618b91D13A2041fb7aC31Bf01C02aD2'

    base:
      weighted:
        weight: 20
        tolerance: 5 # 5% deviation on the expected balance before triggering a rebalance
      bridgeLockTime: 1800 # 30 mins in seconds (required for CCTP latency)
      bridgeMinAcceptedAmount: 3500
      bridge: '0x5C4aFb7e23B1Dc1B409dc1702f89C64527b25975'

    ethereum:
      weighted:
        weight: 20
        tolerance: 5 # 5% deviation on the expected balance before triggering a rebalance
      bridgeLockTime: 1800 # 30 mins in seconds (required for CCTP latency)
      bridgeMinAcceptedAmount: 3500
      bridge: '0xedCBAa585FD0F80f20073F9958246476466205b8'

    optimism:
      weighted:
        weight: 20
        tolerance: 5 # 5% deviation on the expected balance before triggering a rebalance
      bridgeLockTime: 1800 # 30 mins in seconds (required for CCTP latency)
      bridgeMinAcceptedAmount: 3500
      bridge: '0xfB7681ECB05F85c383A5ce4439C7dF5ED12c77DE'

    polygon:
      weighted:
        weight: 20
        tolerance: 5 # 5% deviation on the expected balance before triggering a rebalance
      bridgeLockTime: 1800 # 30 mins in seconds (required for CCTP latency)
      bridgeMinAcceptedAmount: 3500
      bridge: '0xa62F45662809f5F6535b58bae9A572a2EC4A1f84'
