warpRouteId: USDC/lumia
strategy:
  rebalanceStrategy: minAmount
  chains:
    base:
      minAmount:
        min: 2000
        target: 2500
        type: 'absolute'
      bridgeLockTime: 2400 # 40 mins in seconds
      bridge: '0x5C4aFb7e23B1Dc1B409dc1702f89C64527b25975'

    ethereum:
      minAmount:
        min: 10000
        target: 100000
        type: 'absolute'
      bridgeLockTime: 2400 # 40 mins in seconds
      bridge: '0xedCBAa585FD0F80f20073F9958246476466205b8'

    optimism:
      minAmount:
        min: 2000
        target: 2500
        type: 'absolute'
      bridgeLockTime: 2400 # 40 mins in seconds
      bridge: '0xfB7681ECB05F85c383A5ce4439C7dF5ED12c77DE'

    arbitrum:
      minAmount:
        min: 2000
        target: 2500
        type: 'absolute'
      bridgeLockTime: 2400 # 40 mins in seconds
      bridge: '0x8a82186EA618b91D13A2041fb7aC31Bf01C02aD2'
