warpRouteId: USDC/paradex

strategy:
  rebalanceStrategy: weighted
  chains:
    base:
      weighted:
        weight: 15
        tolerance: 3
      bridgeLockTime: 1800 # 30 mins in seconds
      bridgeMinAcceptedAmount: 3000
      bridge: '0x5C4aFb7e23B1Dc1B409dc1702f89C64527b25975'

    ethereum:
      weighted:
        weight: 40
        tolerance: 5
      bridgeLockTime: 1800 # 30 mins in seconds
      bridgeMinAcceptedAmount: 3000
      bridge: '0xedCBAa585FD0F80f20073F9958246476466205b8'

    arbitrum:
      weighted:
        weight: 45
        tolerance: 5
      bridgeLockTime: 1800 # 30 mins in seconds
      bridgeMinAcceptedAmount: 3000
      bridge: '0x8a82186EA618b91D13A2041fb7aC31Bf01C02aD2'
