warpRouteId: USDC/superseed
strategy:
  rebalanceStrategy: minAmount
  chains:
    base:
      minAmount:
        min: 5000
        target: 6000
        type: 'absolute'
      bridgeLockTime: 1800 # 30 mins in seconds
      bridgeMinAcceptedAmount: 2000
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'
      executionType: movableCollateral

    ethereum:
      minAmount:
        min: 5000
        target: 6000
        type: 'absolute'
      bridgeLockTime: 1800 # 30 mins in seconds
      bridgeMinAcceptedAmount: 2000
      bridge: '0x8c8D831E1e879604b4B304a2c951B8AEe3aB3a23'
      executionType: movableCollateral

    ink:
      minAmount:
        min: 5000
        target: 6000
        type: 'absolute'
      bridgeLockTime: 1800 # 30 mins in seconds
      bridgeMinAcceptedAmount: 2000
      bridge: '0x92dFEB6f7Daa532de0F3c75c2091e1607c6593b7'
      executionType: movableCollateral

    optimism:
      minAmount:
        min: 5000
        target: 6000
        type: 'absolute'
      bridgeLockTime: 1800 # 30 mins in seconds
      bridgeMinAcceptedAmount: 2000
      bridge: '0x33e94B6D2ae697c16a750dB7c3d9443622C4405a'
      executionType: movableCollateral

    arbitrum:
      minAmount:
        min: 5000
        target: 6000
        type: 'absolute'
      bridgeLockTime: 1800 # 30 mins in seconds
      bridgeMinAcceptedAmount: 2000
      bridge: '0x4c19c653a8419A475d9B6735511cB81C15b8d9b2'
      executionType: movableCollateral
