artela:
  symbol: WETH.a
  type: synthetic
  owner: "0x801e8135867D65e742eb070A9fC0aD9c2f69B4cd"
  mailbox: "0x3a464f746D23Ab22155710f44dB16dcA53e0775E"
  interchainSecurityModule: "0x0000000000000000000000000000000000000000"
base:
  type: collateral
  token: "0x4200000000000000000000000000000000000006"
  owner: "0x801e8135867D65e742eb070A9fC0aD9c2f69B4cd"
  mailbox: "0xeA87ae93Fa0019a82A727bfd3eBd1cFCa8f64f1D"
  interchainSecurityModule: "0x0000000000000000000000000000000000000000"

