[package]
name = "hyperlane-sealevel-ism-multisig-ism-message-id"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9"
multisig-ism = { path = "../../../multisig-ism" }
num-derive = "0.3"
num-traits = "0.2"
solana-program = "=1.14.13"
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-mailbox = { path = "../../mailbox", features = ["no-entrypoint"] }
thiserror = "1.0"

[dev-dependencies]
solana-program-test = "=1.14.13"
solana-sdk = "=1.14.13"
hex = "0.4.3"

[lib]
crate-type = ["cdylib", "lib"]
