[package]
name = "hyperlane-sealevel-token"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
bs58 = "=0.4.0" # FIXME remove
hyperlane-core = { path = "../../hyperlane-core" }
hyperlane-sealevel-mailbox = { path = "../mailbox", features = ["no-entrypoint"] }
borsh = "0.9"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "=1.14.13"
thiserror = "1.0"

[dependencies.spl-associated-token-account]
version = "=1.1.2"
features = ["no-entrypoint"]
git = "https://github.com/Eclipse-Laboratories-Inc/eclipse-program-library"
branch = "steven/eclipse-1.14.13"

[dependencies.spl-noop]
version = "=0.1.3"
features = ["no-entrypoint"]
git = "https://github.com/Eclipse-Laboratories-Inc/eclipse-program-library"
branch = "steven/eclipse-1.14.13"
[dependencies.spl-token]
version = "=3.5.0"
features = ["no-entrypoint"]
git = "https://github.com/Eclipse-Laboratories-Inc/eclipse-program-library"
branch = "steven/eclipse-1.14.13"

# FIXME Should we actually use 2022 here or try normal token program?
[dependencies.spl-token-2022]
version = "=0.5.0"
features = ["no-entrypoint"]
git = "https://github.com/Eclipse-Laboratories-Inc/eclipse-program-library"
branch = "steven/eclipse-1.14.13"

# [dev-dependencies]
# base64 = "0.13"
# itertools =  "0.10.1"
# log = "0.4"
# testing_logger = "=0.1.1"

[lib]
crate-type = ["cdylib", "lib"]
