[package]
name = "hyperlane-sealevel-token"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
account-utils = { path = "../../libraries/account-utils" }
bs58 = "=0.4.0" # FIXME remove
hyperlane-core = { path = "../../hyperlane-core" }
hyperlane-sealevel-token-lib = { path = "../../libraries/hyperlane-sealevel-token" }
hyperlane-sealevel-mailbox = { path = "../mailbox", features = ["no-entrypoint"] }
hyperlane-sealevel-message-recipient-interface = { path = "../../libraries/message-recipient-interface" }
hyperlane-sealevel-connection-client = { path = "../../libraries/hyperlane-sealevel-connection-client" }
borsh = "0.9"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "=1.14.13"
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }
thiserror = "1.0"

[dependencies.spl-associated-token-account]
version = "=1.1.2"
features = ["no-entrypoint"]
git = "https://github.com/tkporter/eclipse-program-library"
rev = "2f7e864"

[dependencies.spl-noop]
version = "=0.1.3"
features = ["no-entrypoint"]
git = "https://github.com/tkporter/eclipse-program-library"
rev = "2f7e864"
[dependencies.spl-token]
version = "=3.5.0"
features = ["no-entrypoint"]
git = "https://github.com/tkporter/eclipse-program-library"
rev = "2f7e864"

[dependencies.spl-token-2022]
version = "=0.5.0"
features = ["no-entrypoint"]
git = "https://github.com/tkporter/eclipse-program-library"
rev = "2f7e864"

[dev-dependencies]
solana-program-test = "=1.14.13"
solana-sdk = "=1.14.13"
hyperlane-sealevel-ism-rubber-stamp = { path = "../ism/rubber-stamp" }
hyperlane-test-utils = { path = "../../libraries/test-utils" }

[lib]
crate-type = ["cdylib", "lib"]
