{{- if .Values.abacus.kathy.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "abacus-agent.fullname" . }}-kathy
  labels:
    {{- include "abacus-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: kathy
spec:
  selector:
    matchLabels:
      {{- include "abacus-agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kathy
  replicas: 1 
  serviceName: {{ include "abacus-agent.fullname" . }}-kathy
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.abacus.kathy.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "abacus-agent.labels" . | nindent 8 }}
        app.kubernetes.io/component: kathy
        {{- with .Values.podCommonLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.abacus.kathy.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["./kathy"]
        envFrom:
        - configMapRef:
            name: {{ include "abacus-agent.fullname" . }}
        env: 
          {{- if .Values.abacus.kathy.messageInterval }}
          - name: OPT_KATHY_INTERVAL
            value: {{ .Values.abacus.kathy.messageInterval | quote }}
          {{- end }}
          {{- range .Values.abacus.kathy.transactionSigners }}
          {{- if .hexKey }}
          - name: OPT_BASE_SIGNERS_{{ .name | upper }}_KEY
            value: {{ .hexKey }}
          {{- else }}
          - name: OPT_BASE_SIGNERS_{{ .name | upper }}_TYPE
            value: "aws"
          - name: OPT_BASE_SIGNERS_{{ .name | upper }}_ID
            value: {{ .aws.keyId }}
          - name: OPT_BASE_SIGNERS_{{ .name | upper }}_REGION
            value: {{ .aws.region }}
          {{- end }}
          {{- end }}
          {{- if .Values.abacus.tracing.uri }}
          - name: OPT_BASE_TRACING_JAEGER_NAME
            value: {{ include "abacus-agent.fullname" . }}-kathy
          {{- end }}
        resources:
          {{- toYaml .Values.abacus.kathy.resources | nindent 10 }}
        volumeMounts:
        - name: state
          mountPath: {{ .Values.abacus.dbPath }}
        ports: 
        - name: metrics
          containerPort: {{ .Values.abacus.metrics.port }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: state
    spec:
      storageClassName: {{ .Values.storage.storageClass }}
      accessModes: [ {{ .Values.storage.accessModes }} ]
      {{- if .Values.abacus.kathy.storage.snapshot.enabled }}
      dataSource:
        name: {{ .Values.abacus.kathy.storage.snapshot.name }}
        kind: VolumeSnapshot
        apiGroup: snapshot.storage.k8s.io
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.abacus.kathy.storage.size }}
{{- end }}
