cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-sealevel-fee"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
getrandom = { workspace = true, features = ["custom"] }
num-derive.workspace = true
num-traits.workspace = true
solana-program.workspace = true
solana-system-interface.workspace = true
thiserror.workspace = true

access-control = { path = "../../libraries/access-control" }
account-utils = { path = "../../libraries/account-utils" }
hyperlane-core = { path = "../../../main/hyperlane-core" }

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true

hyperlane-test-utils = { path = "../../libraries/test-utils" }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "lib"]
