[package]
name = "hyperlane-fuel"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
fuels.workspace = true
futures.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing-futures.workspace = true
tracing.workspace = true
hex.workspace = true
url.workspace = true
tokio.workspace = true
cynic.workspace = true
fuel-core-client.workspace = true
fuel-core-types.workspace = true
derive_more = { workspace = true, features = ["into", "from"] }
reqwest.workspace = true
derive-new.workspace = true

hyperlane-operation-verifier = { path = "../../applications/hyperlane-operation-verifier" }
hyperlane-core = { path = "../../hyperlane-core", features = ["async"] }
hyperlane-warp-route = { path = "../../applications/hyperlane-warp-route" }

[build-dependencies]
abigen = { path = "../../utils/abigen", features = ["fuels"] }
cynic-codegen = { workspace = true }
