warpRouteId: USDCSTAGE/eclipsemainnet
strategy:
  - rebalanceStrategy: minAmount
    chains:
      base:
        minAmount:
          min: 0.000002
          target: 0.000002
          type: 'absolute'
        bridgeLockTime: 1800 # 30 mins in seconds
        bridge: '0x5C4aFb7e23B1Dc1B409dc1702f89C64527b25975'

      ethereum:
        minAmount:
          min: 0.000002
          target: 0.000002
          type: 'absolute'
        bridgeLockTime: 1800 # 30 mins in seconds
        bridge: '0xedCBAa585FD0F80f20073F9958246476466205b8'

      arbitrum:
        minAmount:
          min: 0.000002
          target: 0.000002
          type: 'absolute'
        bridgeLockTime: 1800 # 30 mins in seconds
        bridge: '0x8a82186EA618b91D13A2041fb7aC31Bf01C02aD2'
