apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kaspa-node-testnet

resources:
  - ../../base

nameSuffix: -testnet

patches:
  - path: kaspad-patch.yaml
    target:
      kind: StatefulSet
      name: kaspad

replicas:
  - name: kaspad
    count: 1
