[package]
name = "hyperlane-sealevel-connection-client"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
access-control = { path = "../access-control" }
borsh.workspace = true
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-mailbox = { path = "../../programs/mailbox", features = ["no-entrypoint"] }
solana-program = "=1.14.13"

[dev-dependencies]
solana-program-test = "=1.14.13"
solana-sdk = "=1.14.13"

[lib]
crate-type = ["cdylib", "lib"]
