[package]
name = "hyperlane-sealevel-connection-client"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
solana-program.workspace = true

access-control = { path = "../access-control" }
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-mailbox = { path = "../../programs/mailbox", features = ["no-entrypoint"] }

[dev-dependencies]

[lib]
crate-type = ["cdylib", "lib"]
