[package]
name = "scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1", default-features = false }
color-eyre = { version = "0.6", optional = true }
config = "0.13"
ethers = { git = "https://github.com/abacus-network/ethers-rs", tag = "2022-09-12-01" }
eyre = "0.6"
prometheus = "0.13"
sea-orm = { version = "0.9", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
thiserror = { version = "1.0", default-features = false }
tokio = { version = "1", features = ["rt", "macros"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.3"

abacus-core = { path = "../../abacus-core" }
abacus-base = { path = "../../abacus-base" }
migration = { path = "migration" }

[dev-dependencies]
tokio-test = "0.4"
abacus-test = { path = "../../abacus-test" }

[features]
default = ["color-eyre"]
oneline-errors = ["abacus-base/oneline-eyre"]
