[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
config = "0.13"
color-eyre = { version = "0.6", optional = true }
serde = {version = "1.0", features = ["derive"]}
serde_json = { version = "1.0", default-features = false }
ethers = { git = "https://github.com/gakonst/ethers-rs", branch = "master" }
ethers-contract = { git = "https://github.com/gakonst/ethers-rs", branch = "master", features=["legacy"] }
thiserror = { version = "1.0", default-features = false }
async-trait = { version = "0.1", default-features = false }
futures-util = "0.3"
eyre = "0.6"
reqwest = { version = "0", features = ["json"]}
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.3"

abacus-core = { path = "../../abacus-core" }
abacus-base = { path = "../../abacus-base" }
abacus-ethereum = { path = "../../chains/abacus-ethereum" }
gelato = { path = "../../gelato" }
prometheus = "0.13"

[dev-dependencies]
tokio-test = "0.4"
abacus-test = { path = "../../abacus-test" }

[features]
default = ["color-eyre"]
oneline-errors = ["abacus-base/oneline-eyre"]
