[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
coingecko = { git = "https://github.com/hyperlane-xyz/coingecko-rs", tag = "2022-09-14-02" }
config = "~0.13.3"
serde = {version = "1.0", features = ["derive"]}
serde_json = { version = "1.0", default-features = false }
ethers = { git = "https://github.com/hyperlane-xyz/ethers-rs", tag = "2023-01-10-04" }
ethers-contract = { git = "https://github.com/hyperlane-xyz/ethers-rs", tag = "2023-01-10-04", features=["legacy"] }
thiserror = "1.0"
async-trait = { version = "0.1", default-features = false }
futures-util = "0.3"
eyre = "0.6"
reqwest = { version = "0", features = ["json"]}
strum = "0.24"
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.3"

hyperlane-core = { path = "../../hyperlane-core" }
hyperlane-base = { path = "../../hyperlane-base" }
hyperlane-ethereum = { path = "../../chains/hyperlane-ethereum" }
gelato = { path = "../../gelato" }
prometheus = "0.13"

[dev-dependencies]
tokio-test = "0.4"
hyperlane-test = { path = "../../hyperlane-test" }

[features]
default = ["hyperlane-base/color-eyre"]
oneline-errors = ["hyperlane-base/oneline-errors"]
