image:
  repository: gcr.io/abacus-labs-dev/hyperlane-agent
  pullPolicy: Always
  tag: 'latest'

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true
  annotations: {}
  name: ''

externalSecrets:
  clusterSecretStore:

podAnnotations: {}
podCommonLabels: {}

storage:
  storageClass: 'standard'
  accessModes: ReadWriteOnce

# -- Hyperlane Overrides
# By Default, Hyperlane Agents load the config baked into the Docker Image
# Pass values here in order to override the values in the config
# Note: For successful operation, one _must_ pass signer keys as
#       they are not baked into the image for security reasons.
hyperlane:
  # Sets the config folder to use
  runEnv: 'default'
  context: 'hyperlane'
  # Sets the base config to be used (switch between Homes)
  baseConfig: 'base.json'
  # Set the DB location to be the volume
  dbPath: /usr/share/hyperlane
  rustBacktrace: full
  tracing:
    # Set the log formatting
    format: json
    # Set the log level
    level: info
    uri: ''
  metrics:
    port: 9090
  aws: # true | false
  gelatoApiKeyRequired: # true | false

  # -- Chain overrides, a sequence
  chains:
    - name: 'alfajores'
      disabled: false
      addresses:
        mailbox:
        multisigIsm:
        interchainGasPaymaster:
      domain:
      rpcStyle: # "ethereum"
      connection:
        type: # "http"

  # Hyperlane Agent Roles
  # Individually Switchable via <role>.enabled
  validator:
    enabled: false
    podAnnotations:
      prometheus.io/port: '9090'
      prometheus.io/scrape: 'true'
    podLabels: {}
    storage:
      size: 10Gi
      snapshot:
        enabled: false
        name: ''
    resources:
      requests:
        cpu: 100m
        memory: 250m
    # -- Transaction Signing keys for home and replica(s)
    signer: {}
    originChainName:
    # -- How long to wait between checking for updates
    configs:
      - interval:
        reorgPeriod:
        checkpointSyncers:

  relayer:
    enabled: false
    podAnnotations:
      prometheus.io/port: '9090'
      prometheus.io/scrape: 'true'
    podLabels: {}
    storage:
      size: 10Gi
      snapshot:
        enabled: false
        name: ''
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
    signers:
      - name: 'kovan'
        # aws:
      - name: 'alfajores'
        # aws:
    config:
      originChainName:
      signedCheckpointPollingInterval:
      multisigCheckpointSyncer:
        threshold:
        checkpointSyncers:

  kathy:
    enabled: false

podSecurityContext:
  fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 250m
  #   memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
