[package]
name = "hyperlane-sealevel-token-collateral"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
account-utils = { path = "../../libraries/account-utils" }
bs58.workspace = true # FIXME remove
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-token-lib = { path = "../../libraries/hyperlane-sealevel-token" }
hyperlane-sealevel-mailbox = { path = "../mailbox", features = ["no-entrypoint"] }
hyperlane-sealevel-message-recipient-interface = { path = "../../libraries/message-recipient-interface" }
hyperlane-sealevel-connection-client = { path = "../../libraries/hyperlane-sealevel-connection-client" }
borsh.workspace = true
num-derive.workspace = true
num-traits.workspace = true
solana-program = "=1.14.13"
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }
thiserror.workspace = true

[dependencies.spl-associated-token-account]
version = "=1.1.2"
features = ["no-entrypoint"]
git = "https://github.com/tkporter/eclipse-program-library"
rev = "2f7e864"

[dependencies.spl-noop]
version = "=0.1.3"
features = ["no-entrypoint"]
git = "https://github.com/tkporter/eclipse-program-library"
rev = "2f7e864"
[dependencies.spl-token]
version = "=3.5.0"
features = ["no-entrypoint"]
git = "https://github.com/tkporter/eclipse-program-library"
rev = "2f7e864"

# FIXME Should we actually use 2022 here or try normal token program?
[dependencies.spl-token-2022]
version = "=0.5.0"
features = ["no-entrypoint"]
git = "https://github.com/tkporter/eclipse-program-library"
rev = "2f7e864"

[dev-dependencies]
solana-program-test = "=1.14.13"
solana-sdk = "=1.14.13"
hyperlane-test-utils = { path = "../../libraries/test-utils" }
hyperlane-sealevel-test-ism = { path = "../ism/test-ism", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
