cargo-features = ["workspace-inheritance"]

[package]
name = "ecdsa-signature"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program.workspace = true
thiserror.workspace = true

hyperlane-core = { path = "../../../main/hyperlane-core" }
# Required to allow dependencies `getrandom` but to preserve determinism required by programs, see
# https://solana.com/news/rust-to-solana
getrandom = { workspace = true, features = ["custom"] }

[lib]
crate-type = ["cdylib", "lib"]
