inboxCount: 1

image:
  repository: gcr.io/clabs-optics/optics-monitor
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

monitor:
  environment: dev
  networks:
  - alfajores
  - kovan
  - gorli
  - mumbai
  - fuji
  config: # Contents of .env file

externalSecrets:
  clusterSecretStore:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9090'

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

