apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent-common.fullname" . }}
  labels:
    {{- include "agent-common.labels" . | nindent 4 }}
data:
  RUN_ENV: {{ .Values.abacus.runEnv | quote }}

  RUN_DOMAINS: {{ .Values.abacus.outboxChains | get "name" | join "," }}
  {{- range .Values.abacus.outboxChains }}
  BASE_CONFIG_{{ .name | upper }}: {{ printf "%s_config.json" (.name | lower ) | quote }}
  {{- end }}
  RUST_BACKTRACE: {{ .Values.abacus.rustBacktrace }}
  HYP_BASE_DB: {{ .Values.abacus.dbPath }}
  HYP_BASE_TRACING_FMT: {{ .Values.abacus.tracing.format }}
  HYP_BASE_TRACING_LEVEL: {{ .Values.abacus.tracing.level }}
  {{- range .Values.abacus.inboxChains }}
{{- include "agent-common.config-env-vars" (dict "config" . "agent_name" "base" "key_name_prefix" (printf "INBOXES_%s_" (.name | upper)) "format" "config_map") | indent 2 }}
  {{- end }}

  {{- range .Values.abacus.outboxChains }}
  {{- if not .disabled }}
  HYP_SCRAPER_{{ .name | upper }}_OUTBOX_DISABLED: "false"
  HYP_SCRAPER_{{ .name | upper }}_OUTBOX_CONNECTION_TYPE: {{ .connection.type }}
  {{- if eq .connection.type "httpQuorum" }}
  HYP_SCRAPER_{{ .name | upper }}_OUTBOX_CONNECTION_URLS: ""
  {{- else }}
  HYP_SCRAPER_{{ .name | upper }}_OUTBOX_CONNECTION_URL: ""
  {{- end }}
  HYP_SCRAPER_{{ .name | upper }}_OUTBOX_NAME: {{ .name | lower }}
  {{- else}}
  HYP_SCRAPER_{{ .name | upper }}_OUTBOX_DISABLED: "true"
  {{- end }}
  {{- end }}

  {{- if .Values.abacus.tracing.uri }}
  HYP_BASE_TRACING_JAEGER_COLLECTOR_URI: {{ .Values.abacus.tracing.uri }}
  {{- end }}
  HYP_BASE_METRICS: {{ .Values.abacus.metrics.port | quote }}
