{{- if .Values.abacus.scraper.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "agent-common.fullname" . }}
  labels:
    {{- include "agent-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: scraper
spec:
  selector:
    matchLabels:
      {{- include "agent-common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: scraper
  replicas: 1 
  serviceName: {{ include "agent-common.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.abacus.scraper.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "agent-common.labels" . | nindent 8 }}
        app.kubernetes.io/component: scraper
        {{- with .Values.podCommonLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.abacus.scraper.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: agent
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["./scraper"]
        envFrom:
        - configMapRef:
            name: {{ include "agent-common.fullname" . }}
        - secretRef:
            name: {{ include "agent-common.fullname" . }}-secret
        env:
{{- include "agent-common.config-env-vars" (dict "config" .Values.abacus.scraper.config "agent_name" "scraper") | indent 10 }}
          {{- range .Values.abacus.scraper.signers }}
{{- include "agent-common.config-env-vars" (dict "config" .keyConfig "agent_name" "base" "key_name_prefix" (printf "SIGNERS_%s_" (.name | upper))) | indent 10 }}
          {{- end }}
          {{- if .Values.abacus.tracing.uri }}
          - name: HYP_BASE_TRACING_JAEGER_NAME
            value: {{ include "agent-common.fullname" . }}-scraper
          {{- end }}
        resources:
          {{- toYaml .Values.abacus.scraper.resources | nindent 10 }}
        volumeMounts:
        - name: state
          mountPath: {{ .Values.abacus.dbPath }}
        ports: 
        - name: metrics
          containerPort: {{ .Values.abacus.metrics.port }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: state
    spec:
      storageClassName: {{ .Values.storage.storageClass }}
      accessModes: [ {{ .Values.storage.accessModes }} ]
      {{- if .Values.abacus.scraper.storage.snapshot.enabled }}
      dataSource:
        name: {{ .Values.abacus.scraper.storage.snapshot.name }}
        kind: VolumeSnapshot
        apiGroup: snapshot.storage.k8s.io
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.abacus.scraper.storage.size }}
{{- end }}
