[package]
name = "serializable-account-meta"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
solana-program.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
