image:
  repository: gcr.io/abacus-labs-dev/abacus-monorepo
  tag:
abacus:
  runEnv: testnet2
  # Used for fetching secrets
  chains: []
cronjob:
  schedule: "*/10 * * * *" # Every 10 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
externalSecrets:
  clusterSecretStore:
