apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent-common.fullname" . }}
  labels:
    {{- include "agent-common.labels" . | nindent 4 }}
data:
  RUN_ENV: {{ .Values.hyperlane.runEnv | quote }}
  ONELINE_BACKTRACES: "true"
  BASE_CONFIG: {{ .Values.hyperlane.baseConfig }}
  RUST_BACKTRACE: {{ .Values.hyperlane.rustBacktrace }}
  HYP_BASE_DB: {{ .Values.hyperlane.dbPath }}
  HYP_BASE_TRACING_FMT: {{ .Values.hyperlane.tracing.format }}
  HYP_BASE_TRACING_LEVEL: {{ .Values.hyperlane.tracing.level }}
  {{- range .Values.hyperlane.chains }}
{{- include "agent-common.config-env-vars" (dict "config" . "agent_name" "base" "key_name_prefix" (printf "CHAINS_%s_" (.name | upper)) "format" "config_map") | indent 2 }}
  {{- end }}
  {{- if .Values.hyperlane.tracing.uri }}
  HYP_BASE_TRACING_JAEGER_COLLECTOR_URI: {{ .Values.hyperlane.tracing.uri }}
  {{- end }}
  HYP_BASE_METRICS: {{ .Values.hyperlane.metrics.port | quote }}
