anvil0:
  interchainSecurityModule: "0x0000000000000000000000000000000000000000"
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  type: collateralMemo
  token: "0x4ed7c70F96B99c776995fB64377f0d4aB3B0e1C1"
  decimals: 18
  name: Foo
  symbol: FOO
  isNft: false
  gas: 1
dymension:
  foreignDeployment: "0x726f757465725f61707000000000000000000000000000ff0000000000000000"
  mailbox: "0x68797065726c616e650000000000000000000000000000000000000000000000"
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  type: syntheticMemo 
  token: "0x726f757465725f61707000000000000000000000000000ff0000000000000000"
  interchainSecurityModule: "0x0000000000000000000000000000000000000000"
  gas: 1
