# A config to define the core contract deployments (crosschain tests)
owner: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
defaultIsm:
  type: 'testIsm'
  threshold: 1 # Number: Signatures required to approve a message
  validators: # Array: List of validator addresses
    - '0xa0ee7a142d267c1f36714e4a8f75612f20a79720'
defaultHook:
  beneficiary: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
  oracleConfig:
    # Cosmos chains (6 decimals)
    hyp1:
      gasPrice: '1'
      tokenDecimals: 6
      tokenExchangeRate: '10000000000'
    hyp2:
      gasPrice: '1'
      tokenDecimals: 6
      tokenExchangeRate: '10000000000'
    hyp3:
      gasPrice: '1'
      tokenDecimals: 6
      tokenExchangeRate: '10000000000'
    # EVM chains (18 decimals)
    anvil1:
      gasPrice: '1'
      tokenDecimals: 18
      tokenExchangeRate: '10000000000'
    anvil2:
      gasPrice: '1'
      tokenDecimals: 18
      tokenExchangeRate: '10000000000'
    anvil3:
      gasPrice: '1'
      tokenDecimals: 18
      tokenExchangeRate: '10000000000'
    anvil4:
      gasPrice: '1'
      tokenDecimals: 18
      tokenExchangeRate: '10000000000'
    # Radix chains (18 decimals)
    radix1:
      gasPrice: '1'
      tokenDecimals: 18
      tokenExchangeRate: '10000000000'
    radix2:
      gasPrice: '1'
      tokenDecimals: 18
      tokenExchangeRate: '10000000000'
    # Sealevel chains (9 decimals)
    sealevel1:
      gasPrice: '1'
      tokenDecimals: 9
      tokenExchangeRate: '10000000000'
  oracleKey: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
  overhead:
    hyp1: 200000
    hyp2: 200000
    hyp3: 200000
    anvil1: 200000
    anvil2: 200000
    anvil3: 200000
    anvil4: 200000
    radix1: 200000
    radix2: 200000
    sealevel1: 200000
  owner: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
  type: interchainGasPaymaster
requiredHook:
  type: merkleTreeHook
