[package]
name = "hyperlane-test-utils"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
hyperlane-sealevel-mailbox = { path = "../../programs/mailbox", features = ["no-entrypoint"] }
hyperlane-sealevel-ism-rubber-stamp = { path = "../../programs/ism/rubber-stamp" }
solana-program = "=1.14.13"
solana-program-test = "=1.14.13"
solana-sdk = "=1.14.13"

[dependencies.spl-token-2022]
version = "=0.5.0"
features = ["no-entrypoint"]
git = "https://github.com/tkporter/eclipse-program-library"
rev = "2f7e864"

[lib]
crate-type = ["cdylib", "lib"]
