[package]
name = "hyperlane-fuel"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0"
async-trait.workspace = true
fuels.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing-futures.workspace = true
tracing.workspace = true
url.workspace = true

hyperlane-core = { path = "../../hyperlane-core" }

# These should only be used if it _must_ be used to interop with the inner library,
# all errors exported from a chain crate should be using thiserror or handrolled to
# make error handling easier.
# eyre = "never"
# anyhow = never

[build-dependencies]
abigen = { path = "../../utils/abigen", features = ["fuels"] }
