[package]
name = "hyperlane-sealevel-message-recipient-interface"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
solana-program.workspace = true
spl-type-length-value.workspace = true

hyperlane-core = { path = "../../../hyperlane-core" }

[lib]
crate-type = ["cdylib", "lib"]
