cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-sealevel-message-recipient-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh.workspace = true
solana-program.workspace = true
spl-discriminator.workspace = true
spl-type-length-value.workspace = true

hyperlane-core = { path = "../../../main/hyperlane-core" }
# Required to allow dependencies `getrandom` but to preserve determinism required by programs, see
# https://solana.com/news/rust-to-solana
getrandom = { workspace = true, features = ["custom"] }

[lib]
crate-type = ["cdylib", "lib"]
