image:
  repository: gcr.io/abacus-labs-dev/hyperlane-warp-monitor
  tag:
hyperlane:
  runEnv: mainnet3
  context: hyperlane
  chains: []
  registryUri: ''
nameOverride: ''
fullnameOverride: ''
externalSecrets:
  clusterSecretStore:
