arbitrum:
  feeContract: "0x7F9587890bffa80F293705251710b92e018C118D"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
  transferRouter: "0xEe896e52b87D8186f41b9F6388C9c8a2cEBAaAc1"
base:
  feeContract: "0x5C093Db84be846C0DEe0BA87b4C447D924683573"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
  transferRouter: "0xe54CDbb0544E48349FcE92b0c3D30eeE9e474bc2"
ethereum:
  feeContract: "0x60ad6dDAEc4637De029b745a39A7dE439C6E2EC8"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
  transferRouter: "0x41cdCd1D59ab8f109CDd01578646B73c54c5CEd2"
optimism:
  feeContract: "0x6E5aF1263c7C4cBcbd3DcdEe1E9e861ae4b0aD7e"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"
  transferRouter: "0x90e90C3EBeb23655929e606CA837248DdCca6935"
polygon:
  feeContract: "0x14831c708c08E1D8B918c01c9253cD400E88A739"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
  transferRouter: "0x939F5257d09fa038D922abEb1b83c7083577Cb7a"
unichain:
  feeContract: "0x3194eAaD87beb9fEFCe980CDe3BfDa441371C103"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0x078D782b760474a361dDA0AF3839290b0EF57AD6"
  transferRouter: "0x81C870cd23d9aD3Bf31353394C43BF13DCF9840C"
