arbitrum:
  feeContract: "0x7F9587890bffa80F293705251710b92e018C118D"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
  transferRouter: "0xEe896e52b87D8186f41b9F6388C9c8a2cEBAaAc1"
base:
  feeContract: "0x8A650bbEe362C004f7B4DeA2b5FC2F6b8d9A59F6"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
  transferRouter: "0x5943F244730DC5ac6B05Cc11581d1989D849e443"
ethereum:
  feeContract: "0x60ad6dDAEc4637De029b745a39A7dE439C6E2EC8"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
  transferRouter: "0x41cdCd1D59ab8f109CDd01578646B73c54c5CEd2"
optimism:
  feeContract: "0x1AaB76AD1ba98bC208E6517502059EEfeBef2765"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"
  transferRouter: "0xc3B55Fc117F3b3A30dF91A69AeF392e314dD240A"
polygon:
  feeContract: "0x14831c708c08E1D8B918c01c9253cD400E88A739"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"
  transferRouter: "0x939F5257d09fa038D922abEb1b83c7083577Cb7a"
unichain:
  feeContract: "0x3194eAaD87beb9fEFCe980CDe3BfDa441371C103"
  owner: "0x3e0A78A330F2b97059A4D507ca9d8292b65B6FB5"
  token: "0x078D782b760474a361dDA0AF3839290b0EF57AD6"
  transferRouter: "0x81C870cd23d9aD3Bf31353394C43BF13DCF9840C"
