[package]
name = "hyperlane-core"
version = "0.1.0"
edition = "2021"

[dependencies]
auto_impl = "1.0"
lazy_static = "1.4"
# TODO Use upstream primitive_types
primitive-types = { branch = "steven/primitive-types-impl-borsh", features = ["impl-borsh", "impl-serde"], git = "ssh://git@github.com/Eclipse-Laboratories-Inc/parity-common" }
sha3 = "0.10.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
num-traits = "0.2"
num-derive = "0.3"

# https://github.com/solana-labs/solana/blob/master/docs/src/developing/on-chain-programs/developing-rust.md#depending-on-rand
getrandom = { version = "0.2.2", features = ["custom"] }

borsh = "0.9.3"
bs58 = "=0.4.0"

[dev-dependencies]
serde_json = "1.0"
