[package]
name = "hyperlane-sovereign"
version = "0.1.0"
edition.workspace = true

[dependencies]
hyperlane-core = { path = "../../hyperlane-core", features = ["async"] }

anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bech32.workspace = true
bytes.workspace = true
ethers.workspace = true
futures.workspace = true
k256.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sha3.workspace = true
tokio = { workspace = true, features = ["fs", "macros"] }
tracing.workspace = true
url.workspace = true
hex.workspace = true
num-traits.workspace = true

ed25519-dalek = "2.1.1"
sov-universal-wallet = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip", branch = "nightly", features = ["serde"] }
tokio-tungstenite = "0.23"

[features]
default = []
