cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-sealevel-mailbox"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
no-spl-noop = []

[dependencies]
borsh.workspace = true
bs58.workspace = true # FIXME remove
num-derive.workspace = true
num-traits.workspace = true
solana-program.workspace = true
thiserror.workspace = true
spl-noop.workspace = true
getrandom.workspace = true

access-control = { path = "../../libraries/access-control" }
account-utils = { path = "../../libraries/account-utils" }
hyperlane-core = { path = "../../../hyperlane-core" }
hyperlane-sealevel-interchain-security-module-interface = { path = "../../libraries/interchain-security-module-interface" }
hyperlane-sealevel-message-recipient-interface = { path = "../../libraries/message-recipient-interface" }
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }

[dev-dependencies]
base64.workspace = true
itertools.workspace = true
log.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
