[package]
name = "hyperlane-sealevel-mailbox"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
hyperlane-core = { path = "../../hyperlane-core" }
borsh = "0.9"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "=1.14.13"
thiserror = "1.0"

bs58 = "=0.4.0" # FIXME remove

[dependencies.spl-noop]
version = "=0.1.3"
features = ["no-entrypoint"]
path = "/Users/trevor/eclipse-program-library/account-compression/programs/noop"

[dev-dependencies]
base64 = "0.13"
itertools =  "0.10.1"
log = "0.4"
testing_logger = "=0.1.1"

[lib]
crate-type = ["cdylib", "lib"]
