[package]
name = "hyperlane-sealevel-mailbox"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
hyperlane-core = { path = "../../hyperlane-core" }
borsh = "0.9"
num-derive = "0.3"
num-traits = "0.2"
solana-program = { version = "=1.14.3", path = "/Users/steven/code/eclipse-labs/eclipse/sdk/program" }
thiserror = "1.0"

[dev-dependencies]
base64 = "0.13"
itertools =  "0.10.1"
log = "0.4"
testing_logger = "=0.1.1"

[lib]
crate-type = ["cdylib", "lib"]
