image:
  repository: gcr.io/abacus-labs-dev/hyperlane-rebalancer
  tag:
warpRouteId: ''
hyperlane:
  runEnv: mainnet3
  context: hyperlane
  registryUri: ''
  rebalancerConfig: ''
  withMetrics: true
  # Used for fetching private RPC secrets
  chains: []
nameOverride: ''
fullnameOverride: ''
externalSecrets:
  clusterSecretStore:
