image:
  repository: gcr.io/abacus-labs-dev/hyperlane-rebalancer
  tag:
hyperlane:
  runEnv:
  context: hyperlane
  registryUri: ''
  registryCommit: ''
  rebalancerConfigFile: ''
  withMetrics: true
nameOverride: ''
fullnameOverride: ''
externalSecrets:
  clusterSecretStore:
