# Testnet4-specific configuration for shovel-indexer
# Usage: helm install shovel ./shovel-indexer -f values.yaml -f values-testnet.yaml

hyperlane:
  runEnv: testnet4
  chains: 'basesepolia'

shovel:
  startBlock: '37880000'

externalSecrets:
  databaseUrlSecretKey: hyperlane-testnet4-indexer-db
