[package]
name = "dymension-kaspa"
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license-file = { workspace = true }
publish = { workspace = true }
version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
bech32 = { workspace = true }
cosmrs = { workspace = true, features = ["tokio", "grpc", "rpc"] }
crypto = { path = "../../utils/crypto" }
derive-new = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-tls = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
protobuf = { workspace = true }
ripemd = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
sha256 = { workspace = true }
tendermint = { workspace = true, features = ["rust-crypto", "secp256k1"] }
tendermint-rpc = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

tonic = { workspace = true, features = [
    "transport",
    "tls",
    "tls-roots",
    "tls-native-roots",
] }
rustls = { workspace = true }
tower.workspace = true
tower-http = { workspace = true, features = ["limit"] }
pin-project.workspace = true
tracing = { workspace = true }
tracing-futures = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true }
axum = { workspace = true }
dym-kas-validator = { path = "../../../../dymension/libs/kaspa/lib/validator", package="validator"}
dym-kas-relayer = { path = "../../../../dymension/libs/kaspa/lib/relayer" , package="relayer"}
dym-kas-core = { path = "../../../../dymension/libs/kaspa/lib/core" , package="core"}
dym-kas-bridge = { path = "../../../../dymension/libs/kaspa/lib/bridge" , package="bridge"}
dym-kas-api = { path = "../../../../dymension/libs/kaspa/lib/api" , package="openapi"}
dym-kas-kms = { path = "../../../../dymension/libs/kaspa/lib/kms", package="dym-kas-kms"}
dymension-kaspa-hl-constants = { path = "../dymension-kaspa-hl-constants" }
eyre = { workspace = true }
bytes = { workspace = true }
prometheus = { workspace = true }

hyperlane-metric = { path = "../../hyperlane-metric" }
hyperlane-core = { path = "../../hyperlane-core", features = ["async"] }
hyperlane-cosmwasm-interface = { workspace = true }
hyperlane-operation-verifier = { path = "../../applications/hyperlane-operation-verifier" }
hyperlane-warp-route = { path = "../../applications/hyperlane-warp-route" }
hyperlane-cosmos = { path = "../hyperlane-cosmos" }
hyperlane-cosmos-rs = { package = "hyperlane-cosmos-dymension-rs", git = "https://github.com/dymensionxyz/hyperlane-cosmos-rs", rev = "4cde36b" }

# Kaspa

kaspa-consensus-core = { workspace = true }
kaspa-txscript = { workspace = true }
kaspa-wallet-pskt = { workspace = true }
kaspa-wrpc-client = { workspace = true }
kaspa-addresses = { workspace = true }
kaspa-wallet-core = { workspace = true }
kaspa-wallet-keys = { workspace = true }
kaspa-rpc-core = { workspace = true }
kaspa-core = { workspace = true }
kaspa-grpc-client = { workspace = true }
kaspa-utils-tower = { workspace = true }
kaspa-hashes = { workspace = true }
kaspa-bip32 = { workspace = true }
kaspa-consensus-client = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
vergen = { version = "8.3.2", features = ["build", "git", "gitcl"] }