environment: testnet

# General deployment configuration
image:
  repository: gcr.io/abacus-labs-dev/hyperlane-monorepo
  # Modify this tag to deploy a new revision.
  # Images can be found here:
  # https://console.cloud.google.com/artifacts/docker/abacus-labs-dev/us/gcr.io/hyperlane-monorepo?inv=1&invt=AbxRMg&project=abacus-labs-dev
  tag: 6cc0eb0-20250528-205256

# In Google Cloud Secret Manager, all secrets need to have a certain prefix in order to be accessible by
# the Cluster Secret Store. For testnet this prefix is "hyperlane-testnet4"
secrets:
  prefix: 'hyperlane-testnet4'

ingress:
  host: testnet-offchain-lookup.services.hyperlane.xyz
  # This needs to be created/looked up in Google Cloud Console
  staticIpName: offchain-lookup-server-testnet

env:
  - name: ENABLED_MODULES
    value: 'cctp,callCommitments'
  - name: HYPERLANE_EXPLORER_URL
    value: 'https://api.hyperlane.xyz/v1/graphql'
  - name: CCTP_ATTESTATION_URL
    value: 'https://iris-api-sandbox.circle.com'
  - name: SERVER_PORT
    value: '3000'
  - name: REGISTRY_URI
    value: 'https://github.com/hyperlane-xyz/hyperlane-registry'
