cargo-features = ["edition2021"]

[workspace]

members = [
    "agents/relayer",
    "agents/scraper",
    "agents/validator",
    "chains/hyperlane-ethereum",
    "chains/hyperlane-fuel",
    "chains/hyperlane-sealevel",
    "ethers-prometheus",
    "hyperlane-base",
    "hyperlane-core",
    "hyperlane-test",
    # "sealevel/programs/ism/rubber-stamp",
    # "sealevel/programs/mailbox",
    # "sealevel/programs/recipient/echo",
    "utils/abigen",
    "utils/backtrace-oneline",
    "utils/hex",
    "utils/run-locally",
]
# FIXME dependency conflicts between solana and hyperlane
exclude = [ "sealevel" ]
# exclude = [ "sealevel/hyperlane-core" ]

[workspace.package]
documentation = "https://docs.hyperlane.xyz"
edition = "2021"
homepage = "https://hyperlane.xyz"
license-file = "../LICENSE.md"
publish = false
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0"
async-trait = { version = "0.1" }
borsh = "0.9"
bs58 = "0.4.0"
color-eyre = { version = "0.6" }
config = "~0.13.3"
derive-new = "0.5"
derive_more = "0.99"
enum_dispatch = "0.3"
ethers = { git = "https://github.com/hyperlane-xyz/ethers-rs", tag = "2023-06-01" }
ethers-contract = { git = "https://github.com/hyperlane-xyz/ethers-rs", tag = "2023-06-01", features = ["legacy"] }
ethers-core = { git = "https://github.com/hyperlane-xyz/ethers-rs", tag = "2023-06-01" }
ethers-providers = { git = "https://github.com/hyperlane-xyz/ethers-rs", tag = "2023-06-01" }
ethers-signers = { git = "https://github.com/hyperlane-xyz/ethers-rs", tag = "2023-06-01", features = ["aws"] }
eyre = "0.6"
fuels = "0.38"
fuels-code-gen = "0.38"
futures = "0.3"
futures-util = "0.3"
Inflector = "0.11.4"
itertools = "0.10"
lazy_static = "1.4"
num = {version = "0.4"}
num-derive = "0.3"
num-traits = "0.2"
paste = "1.0"
prometheus = "0.13"
reqwest = "0.11"
rocksdb = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
static_assertions = "1.1"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0"
tokio = { version = "1", features = ["parking_lot"] }
tracing = { version = "0.1", features = ["release_max_level_debug"] }
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", default-features = false }
url = "2.3"

# FIXME patch primitive types to pull in borsh support. Unfortunately crates in parity-common refer
# to one another with local paths so patching one requires patching most of them.
[patch.crates-io.primitive-types]
branch = "steven/primitive-types-impl-borsh-uint-version-fix"
git = "https://github.com/Eclipse-Laboratories-Inc/parity-common"

[patch.crates-io.rlp]
branch = "steven/primitive-types-impl-borsh-uint-version-fix"
git = "https://github.com/Eclipse-Laboratories-Inc/parity-common"
