[workspace]

members = [
    "optics-core",
    "optics-base",
    "optics-test",
    "chains/optics-ethereum",
    "agents/kathy",
    "agents/updater",
    "agents/relayer",
    "agents/watcher",
    "agents/processor",
    "kms-cli",
]
