# Configs and artifacts for the deployment of Hyperlane Warp Routes
# Between Ethereum and Binance Smart Chain and Lumia
description: Hyperlane Warp Route artifacts
timestamp: '2024-10-18T14:00:00.000Z'
deployer: Abacus Works (Hyperlane)
data:
  config:
    arbitrum:
      protocolType: ethereum
      type: synthetic
      hypAddress: '0x6D251aADfc6Ff69031e01eA39bE3cb5BABf8438f'
      name: Amphor Restaked ETH
      symbol: AMPHRETH
      decimals: 18
    ethereum:
      protocolType: ethereum
      type: collateral
      hypAddress: '0xdc89990a6fdC1C922b841f1d977835628A24Ed57'
      tokenAddress: '0x5fD13359Ba15A84B76f7F87568309040176167cd'
      name: Amphor Restaked ETH
      symbol: AMPHRETH
      decimals: 18
    zircuit:
      protocolType: ethereum
      type: synthetic
      hypAddress: '0x7D5a79539d7B1c9aE5e54d18EEE188840f1Fe4CC'
      name: Amphor Restaked ETH
      symbol: AMPHRETH
      decimals: 18
