# Configs and artifacts for the deployment of Hyperlane Warp Routes
# Between Ethereum and Binance Smart Chain and Lumia
description: Hyperlane Warp Route artifacts
timestamp: '2024-10-18T14:00:00.000Z'
deployer: Abacus Works (Hyperlane)
data:
  config:
    ethereum:
      protocolType: ethereum
      type: collateral
      hypAddress: '0xdD313D475f8A9d81CBE2eA953a357f52e10BA357'
      tokenAddress: '0xd9343a049d5dbd89cd19dc6bca8c48fb3a0a42a7'
      tokenCoingeckoId: 'orion-protocol' # ORN->LUMIA 1:1
      name: Lumia Token
      symbol: LUMIA
      decimals: 18
    bsc:
      protocolType: ethereum
      type: synthetic
      hypAddress: '0x7F39BcdCa8E0E581c1d43aaa1cB862AA1c8C2047'
      name: Lumia Token
      symbol: LUMIA
      decimals: 18
    lumia:
      protocolType: ethereum
      type: native
      hypAddress: '0x6a77331cE28E47c3Cb9Fea48AB6cD1e9594ce0A9'
      name: Lumia Token
      symbol: LUMIA
      decimals: 18
