description: Hyperlane Warp Route artifacts
timestamp: '2024-06-04T16:00:00.000Z'
deployer: Abacus Works (Hyperlane)
data:
  config:
    ethereum:
      protocolType: ethereum
      type: xERC20Lockbox
      name: Renzo Restaked ETH
      symbol: ezETH
      hypAddress: '0xC59336D8edDa9722B4f1Ec104007191Ec16f7087'
      tokenAddress: '0xbf5495Efe5DB9ce00f80364C8B423567e58d2110'
      tokenCoinGeckoId: renzo-restaked-eth
      decimals: 18
    bsc:
      protocolType: ethereum
      type: xERC20
      name: Renzo Restaked ETH
      symbol: ezETH
      hypAddress: '0xE00C6185a5c19219F1FFeD213b4406a254968c26'
      tokenAddress: '0x2416092f143378750bb29b79eD961ab195CcEea5'
      decimals: 18
    arbitrum:
      protocolType: ethereum
      type: xERC20
      name: Renzo Restaked ETH
      symbol: ezETH
      hypAddress: '0xB26bBfC6d1F469C821Ea25099017862e7368F4E8'
      tokenAddress: '0x2416092f143378750bb29b79eD961ab195CcEea5'
      decimals: 18
    optimism:
      protocolType: ethereum
      type: xERC20
      name: Renzo Restaked ETH
      symbol: ezETH
      hypAddress: '0xacEB607CdF59EB8022Cc0699eEF3eCF246d149e2'
      tokenAddress: '0x2416092f143378750bb29b79eD961ab195CcEea5'
      decimals: 18
    base:
      protocolType: ethereum
      type: xERC20
      name: Renzo Restaked ETH
      symbol: ezETH
      hypAddress: '0x2552516453368e42705D791F674b312b8b87CD9e'
      tokenAddress: '0x2416092f143378750bb29b79eD961ab195CcEea5'
      decimals: 18
    blast:
      protocolType: ethereum
      type: xERC20
      name: Renzo Restaked ETH
      symbol: ezETH
      hypAddress: '0x486b39378f99f073A3043C6Aabe8666876A8F3C5'
      tokenAddress: '0x2416092f143378750bb29b79eD961ab195CcEea5'
      decimals: 18
    mode:
      protocolType: ethereum
      type: xERC20
      name: Renzo Restaked ETH
      symbol: ezETH
      hypAddress: '0xC59336D8edDa9722B4f1Ec104007191Ec16f7087'
      tokenAddress: '0x2416092f143378750bb29b79eD961ab195CcEea5'
      decimals: 18
    linea:
      protocolType: ethereum
      type: xERC20
      name: Renzo Restaked ETH
      symbol: ezETH
      hypAddress: '0xC59336D8edDa9722B4f1Ec104007191Ec16f7087'
      tokenAddress: '0x2416092f143378750bb29b79eD961ab195CcEea5'
      decimals: 18
    fraxtal:
      protocolType: ethereum
      type: xERC20
      name: Renzo Restaked ETH
      symbol: ezETH
      hypAddress: '0x3aE8635A4D581d40a6Edfb3f2ED480f9532994F5'
      tokenAddress: '0x2416092f143378750bb29b79eD961ab195CcEea5'
      decimals: 18
    zircuit:
      protocolType: ethereum
      type: xERC20
      name: Renzo Restaked ETH
      symbol: ezETH
      hypAddress: '0x2552516453368e42705D791F674b312b8b87CD9e'
      tokenAddress: '0x2416092f143378750bb29b79eD961ab195CcEea5'
      decimals: 18
