description: Hyperlane Warp Route artifacts
timestamp: '2024-10-17T14:00:00.000Z'
deployer: Abacus Works (Hyperlane)
data:
  config:
    ethereum:
      protocolType: ethereum
      type: collateral
      hypAddress: '0x9AD81058c6C3Bf552C9014CB30E824717A0ee21b'
      tokenAddress: '0x15700B564Ca08D9439C58cA5053166E8317aa138'
      tokenCoinGheckoId: sei-fastusd
      name: fastUSD
      symbol: fastUSD
      decimals: 18
    sei:
      protocolType: ethereum
      type: xERC20
      hypAddress: '0xeA895A7Ff45d8d3857A04c1E38A362f3bd9a076f'
      tokenAddress: '0x37a4dD9CED2b19Cfe8FAC251cd727b5787E45269'
      name: fastUSD
      symbol: fastUSD
      decimals: 18
