[package]
name = "hyperlane-sealevel-interchain-security-module-interface"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
solana-program = "=1.14.13"

[dependencies.spl-type-length-value]
version = "0.1.0"
git = "https://github.com/tkporter/eclipse-program-library"
rev = "2f7e864"
features = ["borsh"]

[lib]
crate-type = ["cdylib", "lib"]
