cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-sealevel-validator-announce"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
# Required to allow dependencies `getrandom` but to preserve determinism required by programs, see
# https://github.com/solana-foundation/developer-content/blob/main/docs/programs/lang-rust.md#depending-on-rand
getrandom = { workspace = true, features = ["custom"] }
solana-program.workspace = true
solana-system-interface.workspace = true
thiserror.workspace = true

account-utils = { path = "../../libraries/account-utils" }
ecdsa-signature = { path = "../../libraries/ecdsa-signature" }
hyperlane-sealevel-mailbox = { path = "../mailbox", features = [
    "no-entrypoint",
] }
hyperlane-core = { path = "../../../main/hyperlane-core" }
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }

[dev-dependencies]
hex.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
solana-system-interface.workspace = true
hyperlane-test-utils = { path = "../../libraries/test-utils" }

[lib]
crate-type = ["cdylib", "lib"]
