[package]
name = "abigen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { git = "https://github.com/hyperlane-xyz/ethers-rs", optional = true, tag = "2023-02-10-01", features = ["legacy"] }
fuels = { version = "0.33", optional = true }
which = {version =  "4.3", optional = true }
Inflector = "0.11"

[features]
default = []
ethers = ["dep:ethers"]
fmt = ["dep:which"]
fuels = ["dep:fuels", "fmt"]
