apiVersion: v1
kind: ConfigMap
metadata:
  name: key-funder-config
  labels:
    {{- include "hyperlane.labels" . | nindent 4 }}
data:
  keyfunder.yaml: |
{{ .Values.hyperlane.keyfunderConfig | indent 4 }}
