apiVersion: batch/v1
kind: CronJob
metadata:
  name: key-funder
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 14400 # 60 * 60 * 4 seconds = 4 hours
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: key-funder
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - ./node_modules/.bin/tsx
            - ./typescript/infra/scripts/funding/fund-keys-from-deployer.ts
            - -e
            - {{ .Values.hyperlane.runEnv }}
            - --context
            - {{ .Values.hyperlane.contextFundingFrom }}
{{- range $context, $roles := .Values.hyperlane.contextsAndRolesToFund }}
            - --contexts-and-roles
            - {{ $context }}={{ join "," $roles }}
{{- end }}
{{- if .Values.hyperlane.connectionType }}
            - --connection-type
            - {{ .Values.hyperlane.connectionType }}
{{- end }}
{{- range $chain, $balance := .Values.hyperlane.desiredBalancePerChain }}
            - --desired-balance-per-chain
            - {{ $chain }}={{ $balance }}
{{- end }}
{{- range $chain, $balance := .Values.hyperlane.desiredKathyBalancePerChain }}
            - --desired-kathy-balance-per-chain
            - {{ $chain }}={{ $balance }}
{{- end }}
            env:
            - name: PROMETHEUS_PUSH_GATEWAY
              value: {{ .Values.infra.prometheusPushGateway }}
            envFrom:
            - secretRef:
                name: key-funder-env-var-secret
            volumeMounts:
            - name: key-funder-addresses-secret
              mountPath: /addresses-secret
          volumes:
          - name: key-funder-addresses-secret
            secret:
              secretName: key-funder-addresses-secret
              defaultMode: 0400
