apiVersion: batch/v1
kind: CronJob
metadata:
  name: key-funder
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 14400
      template:
        metadata:
          labels:
            {{- include "hyperlane.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
          - name: key-funder
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: IfNotPresent
            env:
            - name: LOG_FORMAT
              value: json
            - name: LOG_LEVEL
              value: info
            - name: KEYFUNDER_CONFIG_FILE
              value: /config/keyfunder.yaml
            {{- if .Values.hyperlane.registryUri }}
            - name: REGISTRY_URI
              value: {{ .Values.hyperlane.registryUri }}
            {{- end }}
            {{- if .Values.hyperlane.skipIgpClaim }}
            - name: SKIP_IGP_CLAIM
              value: "true"
            {{- end }}
            envFrom:
            - secretRef:
                name: key-funder-env-var-secret
            volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          volumes:
          - name: config
            configMap:
              name: key-funder-config
