image:
  repository: gcr.io/abacus-labs-dev/hyperlane-key-funder
  tag: latest
hyperlane:
  runEnv: testnet4
  chains: []
  chainsToSkip: []
  registryUri: ''
  keyfunderConfig: ''
  skipIgpClaim: false
  prometheusPushGateway: ''
cronjob:
  schedule: '*/10 * * * *'
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 10
externalSecrets:
  clusterSecretStore:
