[package]
name = "hyperlane-sealevel"
version = "0.1.0"
edition = "2021"

[dependencies]
hyperlane-core = { path = "../../hyperlane-core" }
async-trait = { version = "0.1", default-features = false }
thiserror = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
tracing-futures = { workspace = true }
tracing = { workspace = true }

# FIXME sealevel mailbox contract copypasta deps
borsh = { workspace = true }

# FIXME solana copypasta deps
bincode = "1.3.3"
blake3 = { version = "1.3.1", features = ["digest", "traits-preview"] }
bs58 = { workspace = true }
base64 = "0.13.0"
ed25519-dalek = { version = "=1.0.1", git = "https://github.com/Eclipse-Laboratories-Inc/ed25519-dalek", branch = "steven/fix-deps" }
generic-array = { version = "0.14.5", default-features = false, features = ["serde", "more_lengths"]}
Inflector = { workspace = true }
jsonrpc-core = "18.0.0"
lazy_static = { workspace = true }
log = "0.4.17"
semver = "1.0.10"
serde_bytes = "0.11"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.10.0"
tokio = { workspace = true, features = ["full"] }
url = { workspace = true }
# auto-resolve zstd version to avoid dependency conflicts
zstd = "*"

[dependencies.curve25519-dalek]
version = "3.2.1"
features = ["serde"]
git = "https://github.com/Eclipse-Laboratories-Inc/curve25519-dalek"
branch = "steven/fix-deps"
[dependencies.reqwest]
version = "0.11.11"
default-features = false
features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"]
