apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - kaspad-statefulset.yaml
  - postgres-statefulset.yaml
  - deployments.yaml
  - services.yaml
  - configmap.yaml

labels:
  - pairs:
      project: kaspa-node
      managed-by: kustomize
