[package]
name = "balance-exporter"
version = "0.1.0"
edition = "2021"
description = "Polls chains for optics contract wallet balances and reports them in OpenMetrics format"
authors = ["ember arlynx <ember.arlynx@clabs.co>"]
license = "Apache-2.0"

[dependencies]
tokio = "1"
futures = "0.3"

metrics = "0"
metrics-exporter-prometheus = "0"
serde_json = "1"
serde = "1"
color-eyre = "0"
clap = "3.0.0-beta.4"
human-panic = "1"

abacus-base = { path = "../../abacus-base" }

# SMELL: reaching into the implementation details. abstract eventually.
abacus-ethereum = { path = "../../chains/abacus-ethereum" }
