cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-swisstronik"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
# Main block
async-trait.workspace = true
derive-new.workspace = true
ethers-contract = {git = "https://github.com/SigmaGmbH/ethers-rs.git", branch = "publish", features = []}
ethers-core = {git = "https://github.com/SigmaGmbH/ethers-rs.git", branch = "publish", features = ["legacy"]}
ethers-signers = {git = "https://github.com/SigmaGmbH/ethers-rs.git", branch = "publish", features = ["aws"]}
ethers = {git = "https://github.com/SigmaGmbH/ethers-rs.git", branch = "publish", features = []}
ethers-providers = {git = "https://github.com/SigmaGmbH/ethers-rs.git", branch = "publish", features = []}

futures-util.workspace = true
hex.workspace = true
num.workspace = true
num-traits.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing-futures.workspace = true
tracing.workspace = true
url.workspace = true

hyperlane-core = { path = "../../hyperlane-core" }
ethers-prometheus = { path = "../../ethers-prometheus", features = ["swisstronik"] }

[build-dependencies]
abigen = { path = "../../utils/abigen", features = ["ethers"] }
hyperlane-core = { path = "../../hyperlane-core", features = ["test-utils", "swisstronik"] }
