[package]
name = "hyperlane-tron"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
# Main block
async-trait.workspace = true
dashmap.workspace = true
derive-new.workspace = true
ethers-contract.workspace = true
ethers-core.workspace = true
ethers-signers.workspace = true
ethers.workspace = true
eyre.workspace = true
futures-util.workspace = true
hex.workspace = true
itertools.workspace = true
num.workspace = true
num-traits.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing-futures.workspace = true
tracing.workspace = true
url.workspace = true
bs58.workspace = true

ethers-prometheus = { path = "../../ethers-prometheus", features = ["serde"] }
hyperlane-core = { path = "../../hyperlane-core", features = ["async"] }
hyperlane-ethereum = { path = "../hyperlane-ethereum" }
hyperlane-metric = { path = "../../hyperlane-metric" }
hyperlane-operation-verifier = { path = "../../applications/hyperlane-operation-verifier" }
hyperlane-warp-route = { path = "../../applications/hyperlane-warp-route" }
reqwest-utils = { path = "../../utils/reqwest-utils" }

[build-dependencies]
abigen = { path = "../../utils/abigen", features = ["ethers"] }
hyperlane-core = { path = "../../hyperlane-core", features = ["test-utils"] }

[dev-dependencies]
tracing-test.workspace = true

[features]
default = []
test-utils = []
