[package]
name = "hyperlane-metric"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
derive-new.workspace = true
derive_builder.workspace = true
maplit.workspace = true
prometheus.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
url.workspace = true