{{- if .Values.externalSecrets.clusterSecretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "indexer.fullname" . }}-env-var-secret
  labels:
    {{- include "indexer.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "indexer.fullname" . }}-env-var-secret
    creationPolicy: Owner
  data:
    {{- if .Values.externalSecrets.databaseUrlSecretKey }}
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.databaseUrlSecretKey }}
    {{- end }}
    {{- if .Values.externalSecrets.chainRpcUrlsSecretKey }}
    - secretKey: CHAIN_RPC_URLS
      remoteRef:
        key: {{ .Values.externalSecrets.chainRpcUrlsSecretKey }}
    {{- end }}
{{- end }}
