{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "indexer.fullname" . }}
  labels:
    {{- include "indexer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "indexer.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: 30s
{{- end }}
