[package]
name = "HyperlaneMailBox"
version = "1.0.0"
authors = ["jack@movementlabs.xyz"]

[addresses]
hp_mailbox = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.HyperlaneLibrary]
local = "../library"

[dependencies.HyperlaneISM]
local = "../isms"

[dependencies.HyperlaneRouter]
local = "../router"

[dependencies.HyperlaneIGP]
local = "../igps"

[dev-dependencies]
