[package]
name = "hyperlane-test-send-receiver"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9"
solana-program = "=1.14.13"
hyperlane-sealevel-mailbox = { path = "../mailbox", features = ["no-entrypoint"] }
hyperlane-sealevel-message-recipient-interface = { path = "../../libraries/message-recipient-interface" }

[lib]
crate-type = ["cdylib", "lib"]
