cargo-features = ["workspace-inheritance"]

[package]
name = "account-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh.workspace = true
solana-program.workspace = true
solana-system-interface.workspace = true
spl-discriminator.workspace = true
spl-type-length-value.workspace = true

[dev-dependencies]

[lib]
crate-type = ["cdylib", "lib"]
