cargo-features = ["workspace-inheritance"]

[package]
name = "account-utils"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh.workspace = true
solana-program.workspace = true
spl-type-length-value.workspace = true

# CORE DEPS
#async-trait.workspace = true
#auto_impl = "1.0"
#borsh.workspace = true
#bytes = { version = "1", features = ["serde"] }
#config = { workspace = true, optional = true }
#convert_case = "0.6"
#derive-new.workspace = true
#ethers-core.workspace = true
#eyre.workspace = true
#hex.workspace = true
#itertools.workspace = true
#num = { workspace = true, features = ["serde"] }
#num-derive.workspace = true
#num-traits.workspace = true
#serde.workspace = true
#serde_json.workspace = true
#sha3 = "0.10"
#strum.workspace = true
#thiserror.workspace = true

#lazy_static.workspace = true
#primitive-types = { version = "*", features = ["impl-borsh", "impl-serde"] }
#derive_more.workspace = true

hyperlane-core = { path = "../../../hyperlane-core" }

# Required to allow dependencies `getrandom` but to preserve determinism required by programs, see
# https://github.com/solana-labs/solana/blob/master/docs/src/developing/on-chain-programs/developing-rust.md#depending-on-rand
getrandom = { version = "0.2", features = ["custom"] }

[dev-dependencies]

[lib]
crate-type = ["cdylib", "lib"]
