ethereum:
  type: collateral
  token: "0x73624d2dEF952C77a1f3B5AD995eef53E49639EC"
  owner: "0x9b948CC7CfC4B67262CbbcC37f9d09B61ea6f0E3"
  mailbox: "0xc005dc82818d67AF737725bD4bf75435d065D239"
  interchainSecurityModule: "0x0000000000000000000000000000000000000000"
bsc:
  type: synthetic
  owner: "0xA788b57518bBE602ac94CCEE5ae7E4831a546Bfd"
  mailbox: "0x2971b9Aec44bE4eb673DF1B88cDB57b96eefe8a4"
  interchainSecurityModule: "0x0000000000000000000000000000000000000000"
lumiaprism:
  type: synthetic
  owner: "0x1C4A50f3E9Bfeb268448D19d0D3fe6d58CB0f7BE"
  mailbox: "0x0dF25A2d59F03F039b56E90EdC5B89679Ace28Bc"
  interchainSecurityModule: "0x0000000000000000000000000000000000000000"

