# This is here to satisfy the PR requirements when no rust changes occur.
name: rust

on:
  pull_request:
    branches: [main, v2]
    paths-ignore:
      - 'rust/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rs:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '

  test-rs:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No test required" '

  lint-rs:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No lint required" '
